### ISSUE TITLE
Couldn't import a Framework in staging 

### ISSUE THREAD

**Issue by sedula27** [cassproject/cass-editor#1013]
![Import](https://user-images.githubusercontent.com/93455942/149208839-13623f3c-d342-4acd-a06a-cd6ae7121cf6.PNG)

When I tried to import a framework with 2 Competencies, I could process the file but not import. The status of the file is in processing and the console showed me this errors

@woodkri

**Comment by woodkri** [comment]
A recent dependency update broke several of the imports and exports. I'm hoping to have a fix up by the end of the week.

**Comment by sedula27** [comment]
I couldn't align a framework to assessment or learning opp. It gave me this error.  @woodkri 
![Align](https://user-images.githubusercontent.com/93455942/149342421-107c3d8d-f8f2-43f4-891b-8b96b101240e.PNG)

**Comment by woodkri** [comment]
Both issues should now be fixed.

**Comment by sedula27** [comment]
Import is still not working, i see the same error again @woodkri

**Comment by woodkri** [comment]
I'm having a hard time reproducing the error you're seeing. Could I take a look at the file you're trying to import?

**Comment by jeannekitchens** [comment]
@sedula27 please provide the file to @woodkri

**Comment by sedula27** [comment]
[Aleita test framework - Competencies.csv](https://github.com/cassproject/cass-editor/files/7890541/Aleita.test.framework.-.Competencies.csv)
This is the one i tried to import and when i tried now it gave me the same error

![image](https://user-images.githubusercontent.com/93455942/149974152-9190773e-4fda-42d1-813d-99f378e8d0f4.png)

**Comment by woodkri** [comment]
Ah I assumed you were using a CTDL-ASN formatted CSV. It looks like the CaSS CSV import needs to turn the owner field into an array. I'll work on fixing that.

**Comment by sedula27** [comment]
With credential CSV and JSON LD, import worked fine but when i tried to export it gave me this error
![image](https://user-images.githubusercontent.com/93455942/149979086-e1721a58-f38b-4d83-9ccc-e5ab60193d05.png)

**Comment by woodkri** [comment]
Which framework was this? Did it spin for a long time before showing you that?

**Comment by sedula27** [comment]
Beta Connecting Credentials Framework., this is the framework and in staging. It has been loading from so long no 502 error yet @woodkri

**Comment by woodkri** [comment]
There seems to be a timeout issue with that particular framework. It was imported during the time (June 2019) we were first trying 
the server side imports and the server endpoint hadn't been set server-side so the relation ids are in a weird format. I can look at making the export process more resilient but this framework should be an anomaly.
