### ISSUE TITLE
Sandbox: issues with collection import

### ISSUE THREAD

**Issue by mparsons-ce** [cassproject/cass-editor#1054]
I tried to import a collection, first to the sandbox, and then to staging. 

The main error could be from a type error:
![image](https://user-images.githubusercontent.com/58825866/153086012-eca6b038-8439-4d56-b749-7ec6a95bf48a.png)

As well, there are errors related to Websocket;
**App.vue:369 WebSocket connection to 'wss://staging.credentialengine.org:8443/ws/custom' failed:**

**Missing**
The link to download sample import files only has framework templates. We need templates for a collection.
There is not a specific menu item to import a collection. Is the process the same as for a framework?

**Comment by jeannekitchens** [comment]
@woodkri the Collection upload I tested was on staging.  This information is in slack. The Google sheet I downloaded and uploaded as a CSV is here https://docs.google.com/spreadsheets/d/1qwzqhEuCcAd1mv4lTg_agi7GxxO2t13X/edit?usp=sharing&ouid=100765403558718637226&rtpof=true&sd=true.

**Comment by woodkri** [comment]
I figured out how to do the URL rewrite properly in IIS so that the websocket works. If you remove the webSocketOverride query parameter from the CaSS iframe URL on staging it should work now. @mparsons-ce

**Comment by woodkri** [comment]
This can be closed after the webSocketOverride is removed from the iframe URL.

**Comment by jeannekitchens** [comment]
@mparsons-ce see Kristin's comment above.  Is this addressed?  If not, confirm issue still exists. Otherwise, please close.
