### ISSUE TITLE
An O*Net framework was uploaded to the sandbox and then published but had incorrect URL (prod not sandbox)

### ISSUE THREAD

**Issue by mparsons-ce** [cassproject/cass-editor#1184]
The framework "Home Energy Professional –  Evaluation and Inspection Competency Model" from O*Net was downloaded, uploaded to CaSS, and then published. 
https://www.careeronestop.org/competencymodel/StaticJsonFileDownloadHandler.ashx?file=HEP-Evaluation-Inspection.json
CaSS
https://sandbox.credentialengine.org/publisher/competencies/?frameworkctid=ce-c958bc3e-27e3-44ea-8e9d-e487389345ee

We found the published resource had production registry URIs instead of sandbox ones:
https://sandbox.credentialengineregistry.org/graph/ce-c958bc3e-27e3-44ea-8e9d-e487389345ee

In CaSS, the canonical URL uses the production domain, and the Credential Registry URL uses the sandbox domain:
![image](https://user-images.githubusercontent.com/58825866/185436701-085de64c-1312-4cc3-9868-9b02f5409fb2.png)

The export is using the production domain (appears to be using the Canonical URL rather than the Credential Registry URL).
https://dev.cassproject.org/api/ceasn/fd8930d530bf8c6bf818093c82cc1b32
![image](https://user-images.githubusercontent.com/58825866/185437870-88255e95-f740-4f0e-bbc6-02d9c98b9f03.png)

**Comment by sedula27** [comment]
Convert the Uploaded URL's to registry URL's and do not retain the existing ones if they are not registry URL's
[HEP-Evaluation-Inspection.json](https://github.com/user-attachments/files/16874124/HEP-Evaluation-Inspection.json)

**Comment by miledivovic** [comment]
@sedula27 This might be fixed already as part of another issue, could you verify?

**Comment by sedula27** [comment]
@miledivovic For this the URL's should be dependent on the environment, Publisher shows production url's instead of sandbox
https://sandbox.cass.credentialengine.org/api/ceasn/98eed16aaa20095e7337d849f23f31af

![Image](https://github.com/user-attachments/assets/ab9c224d-8ed8-4167-ab1e-1e8ef5a246f1)

**Comment by miledivovic** [comment]
@sedula27 made an update on sandbox that should fix this if you can verify

**Comment by sedula27** [comment]
@miledivovic Deleted the framework and tried the import but I still see the publisher with production URL

![Image](https://github.com/user-attachments/assets/1a6bf4a2-de01-4454-ba40-e891ea9f0616)

**Comment by miledivovic** [comment]
@sedula27 it should get corrected during the export to ceasn

**Comment by sedula27** [comment]
@miledivovic  The exports shows the corrected publisher, and the UI needs to be updated to reflect that
