### ISSUE TITLE
Ability to duplicate a framework for my own editing purposes.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#26]

**Comment by Lomilar** [comment]
Should be possible via:
Create new framework
Add Competencies -> Search -> Select Framework -> Select All (doesn't exist yet?) -> Copy.

**Comment by Lomilar** [comment]
#13

**Comment by miledivovic** [comment]
Implemented in e3a5228

**Comment by eddavies** [comment]
Tried to duplicate from "mosaic" and nothing happened after clicking copy, just returned me to a list of frameworks to choose competencies to copy from.

**Comment by eddavies** [comment]
Having timeout issues when attempting to copy from large frameworks.

Additionally select all doesn't select all competencies as depicted below:
![select all not selecting all](https://user-images.githubusercontent.com/23706850/33035994-f76b14b8-cde1-11e7-900e-b79649d558b9.PNG)

**Comment by eddavies** [comment]
Also a keyboard shortcut command would be helpful to select all

**Comment by miledivovic** [comment]
Fixed select all and added keyboard shortcut, Shift+Enter in 80227f2 and a36b17b.

Not sure what to do about long copy times.

**Comment by Lomilar** [comment]
I have a deferred n-at-a-time callback pattern that I need to put in ec.base.Task that can handle this.

**Comment by Lomilar** [comment]
Review feedback:
- c.copiedFrom is not in the CASS schema. http://schema.cassproject.org -- Recommend ceasn:derivedFrom
- Will corrupt non-narrows relations.
- Will not copy relations with objects outside of the framework.
- Does not copy CE or any other types of properties, use c.copyFrom(thing) before .generateId()

**Comment by miledivovic** [comment]
Fixed in afcf2ba

I added this https://github.com/cassproject/cass-editor/commit/afcf2ba88f0bb80203cb13b4194209e5b12e68f5#diff-1b78540be6e2feb3d654221a981c55c4L144 to prevent duplicates when copying competencies to be children of an existing competency, not sure if its gonna break something.

**Comment by eddavies** [comment]
Select all working along with its keyboard shortcut, but still getting timeout issues.

**Comment by Lomilar** [comment]
Issue in base library, we require a method of trickling changes, see eduworks/ec#2

**Comment by eddavies** [comment]
After selecting all competencies in a framework, there should be a way to deselect them all (shift-enter).

**Comment by miledivovic** [comment]
Clicking select all again will deselect all.  0f3bb3c

**Comment by eddavies** [comment]
deselect all works.

**Comment by Lomilar** [comment]
Opening separate issue for issue that caused pending.
