### ISSUE TITLE
hasChild and IsChildOf point to incorrect competencies

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#48]
[The full code from which the snippet was taken for this issue can be found at issue #47]

There are a number of [`hasChild`](http://purl.org/ctdlasn/terms/hasChild) and [`isChildOf`](http://purl.org/ctdlasn/terms/isChildOf) properties that point to the wrong objects. Below is an example. Please refer to the CASS framework titled "[Test] Certified Environmental, Safety & Health Trainer (CET)" and the source [Exam Blueprint](https://www.bcsp.org/Portals/0/Assets/DocumentLibrary/CET_Exam_Blueprint.pdf). 

The resource below describes the first competency node in the framework: Domain 1 Communication and Interpersonal Skills * 19%) and is thus a top competency. Note that there are four `isChildOf` properties indicating that this top node has 4 parents that it clearly does not have. The first parent URI:

> `https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Competency/5c6c3603-cecd-4117-ae04-46084fa0e5f01`

points at **no resource** in the graphs. The other three point to child nodes and not parent nodes.

```
  {
    "ceasn:name": {
      "en-us": ""
    },
    "ceasn:inLanguage": [
      "en-US",
      "en-US"
    ],
    "@type": "ceasn:Competency",
    "ceasn:ctid": "ce-9fa34c9c-3984-37ad-8b38-50779622dc94",
    "@id": "https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Competency/f42879d1-8ce1-40a0-9b30-7a1f371881e0/1511618934141",
    "ceasn:isChildOf": [
      "https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Competency/5c6c3603-cecd-4117-ae04-46084fa0e5f0",
      "https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Competency/e1cfe46d-8fcb-490c-9f20-c7a1c82ec34e/1511620246090",
      "https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Competency/3a805cd5-de6d-48b4-8b0e-d19f821842a3/1511620800992",
      "https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Competency/88a197db-282b-476f-b975-a381a8aa199f/1511621593925"
    ],
    "@context": "http://credreg.net/ctdlasn/schema/context/json?releaseID=20170929",
    "ceasn:isPartOf": "https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Framework/2714b9d9-0a08-4222-af88-58f4d6758f69/1511622210773",
    "ceasn:competencyCategory": {
      "en-us": "Domain"
    },
    "ceasn:description": {
      "en-us": "Communication and Interpersonal Skill"
    }
  },
```

**Comment by Lomilar** [comment]
Fixed with latest version of code.

See:
https://cass.credentialengine.org/api/ceasn/schema.cassproject.org.0.3.Framework/2714b9d9-0a08-4222-af88-58f4d6758f69/1511630182476

```json
{
  "ceasn:hasChild":[
    "https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Competency/5c6c3603-cecd-4117-ae04-46084fa0e5f0",
    "https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Competency/e1cfe46d-8fcb-490c-9f20-c7a1c82ec34e/1511620246090",
    "https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Competency/3a805cd5-de6d-48b4-8b0e-d19f821842a3/1511620800992",
    "https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Competency/88a197db-282b-476f-b975-a381a8aa199f/1511621593925"
  ],
  "ceasn:inLanguage":[
    "en-US"
  ],
  "@type":"ceasn:Competency",
  "@id":"https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Competency/f42879d1-8ce1-40a0-9b30-7a1f371881e0/1511618934141",
  "ceasn:isChildOf":[
    "https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Framework/2714b9d9-0a08-4222-af88-58f4d6758f69/1511630182476"
  ],
  "ceasn:isPartOf":[
    "https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Framework/2714b9d9-0a08-4222-af88-58f4d6758f69/1511630182476"
  ],
  "ceasn:competencyCategory":[
    {
      "en-us":"Domain"
    }
  ],
  "ceasn:description":{
    "en-us":"Communication and Interpersonal Skill"
  },
  "ceterms:ctid":"ce-9ad8e53d-4350-36d0-baf2-4e3dc5fc37a3",
  "ceasn:competencyText":{
    "en-us":""
  }
}
```

**Comment by stuartasutton** [comment]
We still have a few problems with the child nodes. You've fixed the problem of hasChild/isChildOf pointing in the wrong direction; but, with the latest version, we still have problems with: (1) URI's in hasChild lists that identify nothing in the graph; and (2) a duplicate child node entry.

### Children URI that reference nothing in the graph

1. Node https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Competency/f42879d1-8ce1-40a0-9b30-7a1f371881e0/1511618934141 has a child that references nothing:

> https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Competency/5c6c3603-cecd-4117-ae04-46084fa0e5f0 

2. Node https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Competency/88a197db-282b-476f-b975-a381a8aa199f/1511621593925 has a node that references nothing:

> https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Competency/f5a7571a-2e6d-4cc2-9f40-6df846ffd82

### Duplicate child nodes

Node https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Competency/e1cfe46d-8fcb-490c-9f20-c7a1c82ec34e/1511620246090 has two child nodes referencing with the same URI  "Instructional technology terminology"

> https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Competency/86890b5b-b028-4bd0-8e18-45d134407586/1511620438749

While there was only one duplicate child node in the small sample, it is likely something that will pop up elsewhere if the cause is not found.

**Comment by Lomilar** [comment]
Cause analysis (more like guesses at this moment):

Children URI that reference nothing:
5c6c3603 and f5a7571a are likely competencies that have been deleted. Need to confirm.

Duplicate child nodes:
86890b5b is likely a relation that was duplicated for some unknown reason while drag/dropping. Drag/drop relation duplication was found.

Exception handling on the editor should be implemented to remedy dangling relations and duplicate relations.

**Comment by Lomilar** [comment]
Covered by #105
