### ISSUE TITLE
Comment Publishing 

### ISSUE THREAD

**Issue by jeannekitchens** [cassproject/cass-editor#651]
The issue with publishing blank comments  was supposed to have been corrected.  During today's webinar when looking at the NICE frameworks, this resurfaced.  @mparsons-ce @woodkri @Lomilar Reply with confirmation this is issue is fixed and with who is responsible for republishing to ensure there are no frameworks published with blank comments 

<img width="2031" alt="Screenshot 2020-04-20 09 09 39" src="https://user-images.githubusercontent.com/20917206/79775757-b64e9d00-8302-11ea-9df6-4a337b71fae0.png">

**Comment by siuc-nate** [comment]
The CaSS output for that framework does not contain empty comments:
https://cass.credentialengine.org/api/ceasn/cf31c5fc1bf4fa191e8d330ba05bfde8

This is probably just old data that needs to be republished.

**Comment by mparsons-ce** [comment]
I republished the framework, and the empty comments are gone
For competency:
https://credentialengineregistry.org/resources/ce-f02843ea-e0e3-4268-b524-af1c2b61ebc6

Before
![image](https://user-images.githubusercontent.com/58825866/79802289-49003380-8325-11ea-950e-71b7bb149b07.png)


After
![image](https://user-images.githubusercontent.com/58825866/79802309-56b5b900-8325-11ea-86bf-3c91dbbcd884.png)

**Comment by mparsons-ce** [comment]
However, I checked a few other DOL frameworks, and some have competency with empty comments.
@siuc-nate Can we search for these using the graph search?

**Comment by siuc-nate** [comment]
Not via the search API - looking for an empty string would probably just match anything with a comment.  However, you could do it with SPARQL directly.

**Comment by siuc-nate** [comment]
These all matched a query for frameworks with competencies with empty string comments:
https://credentialengineregistry.org/graph/ce-7afcbac1-d5cd-4273-89a4-2917d7ac9d22
https://credentialengineregistry.org/graph/ce-001ef2e8-3f11-43b7-9adc-38801341c5b2
https://credentialengineregistry.org/graph/ce-21155df0-ccc4-404d-ad84-00a6559161d6
https://credentialengineregistry.org/graph/ce-342b863a-9530-4acc-a980-52a2d8a48cdd
https://credentialengineregistry.org/graph/ce-77918080-d071-4215-a63c-e507d7d93325
https://credentialengineregistry.org/graph/ce-ee8c01f1-05fe-4d09-99ff-7dd4ec12a571
https://credentialengineregistry.org/graph/ce-820fa9bf-1f1a-412e-b10e-c07d7c570f60
https://credentialengineregistry.org/graph/ce-fef7d964-bacd-41df-b7ec-e50b8ad08321
https://credentialengineregistry.org/graph/ce-45215ecb-bd4d-4999-9f21-643e44c74dac
https://credentialengineregistry.org/graph/ce-726e57e7-737a-4641-a0d9-018cbc81ed24
https://credentialengineregistry.org/graph/ce-226f9c67-8497-4f03-8bd0-6d7b1c072bbc
https://credentialengineregistry.org/graph/ce-5c260fb2-541d-4dce-af4e-d9b2b07633ec
https://credentialengineregistry.org/graph/ce-b8fe47a4-b7dd-4a3d-a163-19e777b9b1b8
https://credentialengineregistry.org/graph/ce-36ef62ad-5118-41f1-b3d2-0b14f2073b24
https://credentialengineregistry.org/graph/ce-27115b6c-bbbc-4ff2-a6e5-49b8e1f022e9
https://credentialengineregistry.org/graph/ce-a59e9bb7-e385-492a-bd50-e63f52349c72
https://credentialengineregistry.org/graph/ce-c277c93c-81ae-4e7c-b930-4c30ce3dc71b
https://credentialengineregistry.org/graph/ce-2d6925c7-e3bc-4ffb-a35f-bab30d8764d1
https://credentialengineregistry.org/graph/ce-b4f7e4d1-bc57-4bd3-86f7-4158ed4a997f
https://credentialengineregistry.org/graph/ce-da3fd37b-b835-4989-8f1c-c0880c192fc8
https://credentialengineregistry.org/graph/ce-a8ad573d-ed45-4d57-9ffb-43f4ea623e9d
https://credentialengineregistry.org/graph/ce-6bdf37a5-644e-46d2-ab9c-1689b9c0a471
https://credentialengineregistry.org/graph/ce-4ef79a9f-ffe5-4f99-8fb3-fc716414586e
https://credentialengineregistry.org/graph/ce-370b8df1-3e08-4956-872f-e4726ad620a5
https://credentialengineregistry.org/graph/ce-02a8adbd-3da9-487c-8f11-3d97cfd7aedb
https://credentialengineregistry.org/graph/ce-74e48846-6a00-4700-9fe5-65ea45284752
https://credentialengineregistry.org/graph/ce-64d8493d-de8d-41db-81e3-4b60e57506c4
https://credentialengineregistry.org/graph/ce-6f48f4bb-9d78-4947-8ab6-4722749f2733

**Comment by stuartasutton** [comment]
Nate, out of curiosity, can you provide the actual SPARQL query.

**Comment by siuc-nate** [comment]
```
PREFIX ceasn: <https://purl.org/ctdlasn/terms/> 
SELECT DISTINCT ?framework WHERE { ?s ceasn:comment ''@en-us . ?s ceasn:isPartOf ?framework .  }
```

**Comment by mparsons-ce** [comment]
Thanks Nate, I will republish these tonight.

**Comment by mparsons-ce** [comment]
@siuc-nate I published all the frameworks in the list. Could you do the SparQL query again just to ensure I didn't miss any?

**Comment by siuc-nate** [comment]
It's the same list as before - the index probably hasn't caught up yet.

**Comment by jeannekitchens** [comment]
@mparsons-ce please check this ahead of our CaSS meeting today and close if this is issue is corrected .

**Comment by siuc-nate** [comment]
It's still the same list. I'm guessing the indexing process for the SPARQL search broke again.

**Comment by siuc-nate** [comment]
The SPARQL index was rebuilt, but the same list of frameworks is still appearing in it.  I'll contact the LT team.

**Comment by mparsons-ce** [comment]
@siuc-nate Do you know if the SparQL issue has been resolved?

**Comment by siuc-nate** [comment]
The query now returns no results, so yes, it appears to be fixed.
